[package]
name = "checklister"
version = "0.3.0"
edition = "2024"
license = "Apache-2.0"

[dev-dependencies]
criterion = "0.6.0"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
eframe = { version = "0.35.0", features = ["persistence"]}
egui_extras = {
    version = "0.35.0",
    features = ["image"]
}
image = {
    version = "0.25.10",
    features = ["png"]
}
rfd = "0.15.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.139"

[[bench]]
name = "hash-bench"
harness = false
