[package]
name = "checklister"
version = "0.2.0"
edition = "2021"
licence = "Apache-2.0"

[dev-dependencies]
criterion = "0.6.0"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
eframe = { version = "0.31.0", features = ["persistence"]}
rfd = "0.15.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.139"

[[bench]]
name = "hash-bench"
harness = false
